<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="wheel_radius"     value="0.1"/>
  <xacro:property name="wheel_width"      value="0.045"/>
  <xacro:property name="wheel_separation" value="0.3517"/>
  <xacro:property name="wheel_torque"     value="5.5"/>
  <xacro:property name="wheel_velocity"   value="1.0"/>

  <xacro:property name="deg_to_rad" value="0.01745329251994329577" />
  <xacro:property name="mesh_scale"   value="0.001"/>

  <!-- Base link -->
  <xacro:property name="base_link_z" value="0.09877"/>

  <link name="base_link">
    <inertial>
      <origin xyz="-0.00381 0.00312 0.43029" rpy="0 0 0" />
      <mass value="64.24132" />
      <inertia ixx="11.896358" ixy="0.001117" ixz="-0.200645"
               iyy="11.897509" iyz="0.11063"
               izz="0.796967"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://stockbot_description/meshes/base/base_and_cover.stl" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
      </geometry>
      <material name="DarkGrey" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://stockbot_description/meshes/base/base_and_cover.stl" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
      </geometry>
      <material name="DarkGrey" />
    </collision>
  </link>

  <!-- Base footprint -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 0.09877" rpy="0 0 0" />
    <child link="base_footprint" />
    <parent link="base_link"/>
  </joint>

  <!-- left wheel -->
  <link name="wheel_left_link">
    <inertial>
      <origin xyz="0 ${0.02086 * -1.0} -0.00259" rpy="0 0 0"/>
      <mass value="4.31508"/>
      <inertia ixx="0.013545" ixy="0" ixz="0"
               iyy="0.010718" iyz="${-0.000921 * -1.0}"
               izz="0.013395"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${-90 * deg_to_rad} 0"/>
      <geometry>
        <mesh filename="package://stockbot_description/meshes/wheels/wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_footprint"/>
    <child link="wheel_left_link"/>
    <origin xyz="0 ${-1.0 * -wheel_separation / 2} 0" rpy="${-90 * -1.0 * deg_to_rad} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="${wheel_torque}" velocity="${wheel_velocity / wheel_radius}"/>
  </joint>

  <!-- right wheel -->
  <link name="wheel_right_link">
    <inertial>
      <origin xyz="0 ${0.02086 * 1.0} -0.00259" rpy="0 0 0"/>
      <mass value="4.31508"/>
      <inertia ixx="0.013545" ixy="0" ixz="0"
               iyy="0.010718" iyz="${-0.000921 * 1.0}"
               izz="0.013395"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${-90 * deg_to_rad} 0"/>
      <geometry>
        <mesh filename="package://stockbot_description/meshes/wheels/wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_footprint"/>
    <child link="wheel_right_link"/>
    <origin xyz="0 ${1.0 * -wheel_separation / 2} 0" rpy="${-90 * 1.0 * deg_to_rad} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="${wheel_torque}" velocity="${wheel_velocity / wheel_radius}"/>
  </joint>
</robot>
